"""Normalization package for GALI platform ingestion."""

from gali_core.normalize.core_normalizer import (
    normalize_commodity_prices,
    normalize_company_financials,
    normalize_company_performance,
    normalize_mining_companies,
    normalize_mining_contracts,
    normalize_mining_licenses,
    normalize_mining_sites,
    normalize_sales_destinations,
    parse_date_safe,
    parse_float_safe,
    upsert_commodity_prices,
    upsert_company_financials,
    upsert_company_performance,
    upsert_mining_companies,
    upsert_mining_contracts,
    upsert_mining_licenses,
    upsert_mining_sites,
    upsert_sales_destinations,
)
from gali_core.normalize.market_normalizer import (
    normalize_daily_close,
    normalize_foreign_flow,
    normalize_idx_companies,
    upsert_daily_close,
    upsert_foreign_flow,
    upsert_idx_companies,
)

__all__ = [
    "normalize_commodity_prices",
    "normalize_company_financials",
    "normalize_company_performance",
    "normalize_daily_close",
    "normalize_foreign_flow",
    "normalize_idx_companies",
    "normalize_mining_companies",
    "normalize_mining_contracts",
    "normalize_mining_licenses",
    "normalize_mining_sites",
    "normalize_sales_destinations",
    "parse_date_safe",
    "parse_float_safe",
    "upsert_commodity_prices",
    "upsert_company_financials",
    "upsert_company_performance",
    "upsert_daily_close",
    "upsert_foreign_flow",
    "upsert_idx_companies",
    "upsert_mining_companies",
    "upsert_mining_contracts",
    "upsert_mining_licenses",
    "upsert_mining_sites",
    "upsert_sales_destinations",
]
