/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Liveness probe returning 200 OK if FastAPI process is alive.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Readiness probe checking database connectivity and published metric run availability.
         */
        get: operations["readiness_check_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/issuers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Issuers
         * @description List all in-universe issuers with summary ground truth scores, RLI, RBV, and data quality badges.
         */
        get: operations["list_issuers_v1_issuers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/issuers/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Issuer Detail
         * @description Retrieve full fundamental intelligence report for an issuer (M1–M9, linked entities, and audit evidence).
         */
        get: operations["get_issuer_detail_v1_issuers__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/issuers/{symbol}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Issuer Graph
         * @description Generate interactive node-edge graph connecting listed issuer -> operating subsidiaries -> mining sites -> licenses -> contractors.
         */
        get: operations["get_issuer_graph_v1_issuers__symbol__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mining Sites Geojson
         * @description Retrieve verified mining concession sites as an RFC 7946 GeoJSON FeatureCollection.
         */
        get: operations["get_mining_sites_geojson_v1_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metric Rankings
         * @description Retrieve filtered leaderboard rankings for a specific fundamental or market metric.
         */
        get: operations["get_metric_rankings_v1_rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cost-curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get National Cost Curve
         * @description Retrieve national cumulative cost curve curve points, unit margins, and benchmark breakevens.
         */
        get: operations["get_national_cost_curve_v1_cost_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Scenario Simulation
         * @description Execute live parametric macroeconomic, trade restriction, and concession shock simulations.
         */
        post: operations["run_scenario_simulation_v1_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flow-overlay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Flow Overlay
         * @description Retrieve market capital flows, institutional positioning, and divergence spreads across universe issuers.
         */
        get: operations["get_flow_overlay_v1_flow_overlay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Coverage Report
         * @description Retrieve full audit metrics detailing database coverage, entity resolution rates, and GPS coordinates completeness.
         */
        get: operations["get_data_coverage_report_v1_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CostCurvePoint */
        CostCurvePoint: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Cash Cost Per Ton Usd */
            cash_cost_per_ton_usd: number;
            /** Annual Volume Mt */
            annual_volume_mt: number;
            /** Cumulative Volume Mt */
            cumulative_volume_mt: number;
            /** Cost Curve Percentile */
            cost_curve_percentile: number;
            /** Realized Price Per Ton Usd */
            realized_price_per_ton_usd?: number | null;
            /** Unit Margin Usd */
            unit_margin_usd?: number | null;
            /** Breakeven Benchmark Price Usd */
            breakeven_benchmark_price_usd?: number | null;
        };
        /** CostCurveResponse */
        CostCurveResponse: {
            /**
             * Commodity
             * @default Coal
             */
            commodity: string;
            /** Run Id */
            run_id: string;
            /** Benchmark Price Usd */
            benchmark_price_usd: number;
            /** Points */
            points: components["schemas"]["CostCurvePoint"][];
            /** Partial Issuers Excluded */
            partial_issuers_excluded?: string[];
        };
        /** CoverageItem */
        CoverageItem: {
            /** Layer */
            layer: string;
            /** Entity */
            entity: string;
            /** Numerator */
            numerator: number;
            /** Denominator */
            denominator: number;
            /** Coverage Pct */
            coverage_pct: number;
            /** Description */
            description: string;
        };
        /** DataCoverageResponse */
        DataCoverageResponse: {
            /**
             * Gate Decision
             * @default GO MENYEMPIT (Coal Titans — 9 Emiten)
             */
            gate_decision: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Credits Used */
            credits_used: number;
            /**
             * Credits Cap
             * @default 1000
             */
            credits_cap: number;
            /** Metrics */
            metrics: components["schemas"]["CoverageItem"][];
            /** In Universe Issuers */
            in_universe_issuers: {
                [key: string]: unknown;
            }[];
        };
        /** FlowOverlayResponse */
        FlowOverlayResponse: {
            /** Run Id */
            run_id: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Issuers */
            issuers: components["schemas"]["IssuerFlowItem"][];
        };
        /** GeoJSONFeature */
        GeoJSONFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Id */
            id?: string | null;
            geometry: components["schemas"]["GeoJSONGeometry"];
            properties: components["schemas"]["MiningSiteProperties"];
        };
        /** GeoJSONFeatureCollection */
        GeoJSONFeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["GeoJSONFeature"][];
            /** Total Features */
            total_features: number;
        };
        /** GeoJSONGeometry */
        GeoJSONGeometry: {
            /**
             * Type
             * @default Point
             * @constant
             */
            type: "Point";
            /**
             * Coordinates
             * @description [longitude, latitude]
             */
            coordinates: number[];
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Label */
            label: string;
            /** Weight */
            weight?: number | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Type
             * @enum {string}
             */
            type: "issuer" | "operating_company" | "mining_site" | "license" | "contractor";
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @example ok
             */
            status: string;
            /**
             * Version
             * @default v1.0.0
             */
            version: string;
        };
        /** IssuerDetail */
        IssuerDetail: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sub Sector */
            sub_sector?: string | null;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Run Id */
            run_id: string;
            /** Data Quality */
            data_quality: string;
            /** Rli Years */
            rli_years?: number | null;
            /** Implied Life Years */
            implied_life_years?: number | null;
            /** Reserve Life Gap Years */
            reserve_life_gap_years?: number | null;
            /** Attributable Gross Profit Usd */
            attributable_gross_profit_usd?: number | null;
            /** Reserve Backed Value Usd */
            reserve_backed_value_usd?: number | null;
            /** Market Cap Idr */
            market_cap_idr?: number | null;
            /** Market Cap Usd */
            market_cap_usd?: number | null;
            /** Rbv Gap Pct */
            rbv_gap_pct?: number | null;
            /** License Cliff 1Y */
            license_cliff_1y?: number | null;
            /** License Cliff 3Y */
            license_cliff_3y?: number | null;
            /** License Cliff 5Y */
            license_cliff_5y?: number | null;
            /** Cnc Coverage Pct */
            cnc_coverage_pct?: number | null;
            /** Weighted Days To Expiry */
            weighted_days_to_expiry?: number | null;
            /** Cash Cost Per Ton Usd */
            cash_cost_per_ton_usd?: number | null;
            /** Realized Price Per Ton Usd */
            realized_price_per_ton_usd?: number | null;
            /** Unit Margin Usd */
            unit_margin_usd?: number | null;
            /** Breakeven Benchmark Price Usd */
            breakeven_benchmark_price_usd?: number | null;
            /** Cost Curve Percentile */
            cost_curve_percentile?: number | null;
            /** Weighted Cv Kcal */
            weighted_cv_kcal?: number | null;
            /** Benchmark Grade */
            benchmark_grade?: string | null;
            /** Benchmark Price Usd */
            benchmark_price_usd?: number | null;
            /** Quality Discount Pct */
            quality_discount_pct?: number | null;
            /** Destination Hhi */
            destination_hhi?: number | null;
            /** Top Destination */
            top_destination?: string | null;
            /** Top Destination Pct */
            top_destination_pct?: number | null;
            /** Contractor Hhi */
            contractor_hhi?: number | null;
            /** Contract Cliff 12M */
            contract_cliff_12m?: number | null;
            /** Ground Truth Score */
            ground_truth_score?: number | null;
            /** Component Scores */
            component_scores?: {
                [key: string]: number | null;
            };
            /** Confidence */
            confidence?: {
                [key: string]: unknown;
            };
            /** Linked Entities */
            linked_entities?: components["schemas"]["LinkedOperatingEntity"][];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
        };
        /** IssuerFlowItem */
        IssuerFlowItem: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Quadrant */
            quadrant: string | null;
            /** Divergence Spread */
            divergence_spread: number | null;
            /** Rbv Gap Pct */
            rbv_gap_pct: number | null;
            /** Ground Truth Score */
            ground_truth_score: number | null;
            /** Net Foreign Flow 30D Idr */
            net_foreign_flow_30d_idr: number | null;
            /** Market Cap Idr */
            market_cap_idr: number | null;
        };
        /** IssuerGraphResponse */
        IssuerGraphResponse: {
            /** Symbol */
            symbol: string;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** IssuerScenarioImpactSchema */
        IssuerScenarioImpactSchema: {
            /** Symbol */
            symbol: string;
            /** Baseline Rbv Usd */
            baseline_rbv_usd: number | null;
            /** Post Shock Rbv Usd */
            post_shock_rbv_usd: number | null;
            /** Delta Rbv Usd */
            delta_rbv_usd: number | null;
            /** Delta Rbv Pct */
            delta_rbv_pct: number | null;
            /** Baseline Rank */
            baseline_rank: number | null;
            /** Post Shock Rank */
            post_shock_rank: number | null;
            /** Rank Change */
            rank_change: number | null;
            /** Volume At Risk Pct */
            volume_at_risk_pct: number;
            /** Revenue At Risk Usd */
            revenue_at_risk_usd: number;
            /** Post Shock Gp Usd */
            post_shock_gp_usd: number | null;
            /** Is Partial */
            is_partial: boolean;
        };
        /** IssuerSummary */
        IssuerSummary: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sub Sector */
            sub_sector?: string | null;
            /**
             * Data Quality
             * @description 'LENGKAP' (complete) or 'PARSIAL' (partial)
             */
            data_quality: string;
            /**
             * Ground Truth Score
             * @description M8 composite score (0-100)
             */
            ground_truth_score?: number | null;
            /**
             * Confidence Pct
             * @description Effective weight utilized (0-100%)
             * @default 100
             */
            confidence_pct: number;
            /**
             * Rli Years
             * @description M1 Reserve Life Index
             */
            rli_years?: number | null;
            /**
             * Reserve Backed Value Usd
             * @description M2 Reserve-Backed Value in USD
             */
            reserve_backed_value_usd?: number | null;
            /** Market Cap Idr */
            market_cap_idr?: number | null;
            /** Market Cap Usd */
            market_cap_usd?: number | null;
            /**
             * Rbv Gap Pct
             * @description M2 valuation premia / discount %
             */
            rbv_gap_pct?: number | null;
            /**
             * License Cliff 3Y
             * @description M3 3-year concession expiry %
             */
            license_cliff_3y?: number | null;
            /**
             * Cash Cost Per Ton Usd
             * @description M4 unit cash cost FOB
             */
            cash_cost_per_ton_usd?: number | null;
            /**
             * Top Destination
             * @description M6 top export market
             */
            top_destination?: string | null;
            /** Top Destination Pct */
            top_destination_pct?: number | null;
        };
        /** LinkedOperatingEntity */
        LinkedOperatingEntity: {
            /** Company Slug */
            company_slug: string;
            /** Name */
            name?: string | null;
            /** Effective Ownership Pct */
            effective_ownership_pct: number;
            /** Confidence */
            confidence?: number | null;
            /** Method */
            method?: string | null;
        };
        /** MiningSiteProperties */
        MiningSiteProperties: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Commodity */
            commodity?: string | null;
            /** Company Slug */
            company_slug?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Issuer Symbol */
            issuer_symbol?: string | null;
            /** Province */
            province?: string | null;
            /** City */
            city?: string | null;
            /** Project Name */
            project_name?: string | null;
            /** Production Volume Mt */
            production_volume_mt?: number | null;
            /**
             * Is In Universe
             * @default false
             */
            is_in_universe: boolean;
        };
        /** RankingItem */
        RankingItem: {
            /** Rank */
            rank: number;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Data Quality */
            data_quality: string;
            /** Metric Value */
            metric_value: number | null;
            /** Formatted Value */
            formatted_value: string;
            /** Confidence Pct */
            confidence_pct?: number | null;
        };
        /** RankingsResponse */
        RankingsResponse: {
            /** Metric */
            metric: string;
            /** Run Id */
            run_id: string;
            /** Items */
            items: components["schemas"]["RankingItem"][];
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Status
             * @default ready
             * @example ready
             */
            status: string;
            /** Database */
            database: boolean;
            /** Redis */
            redis: boolean;
            /** Published Run Id */
            published_run_id?: string | null;
        };
        /** ScenarioResponse */
        ScenarioResponse: {
            params: components["schemas"]["ScenarioShockRequest"];
            /** Impacts */
            impacts: components["schemas"]["IssuerScenarioImpactSchema"][];
            /** Execution Time Ms */
            execution_time_ms: number;
        };
        /** ScenarioShockRequest */
        ScenarioShockRequest: {
            /**
             * Price Shock Pct
             * @description Percentage shock to commodity benchmark price (-1.0 to 2.0)
             * @default 0
             * @example -0.2
             */
            price_shock_pct: number;
            /**
             * Destination Shocks
             * @description Country-specific volume demand shocks (0.0 to 1.0 reduction)
             * @example {
             *       "China": 0.3,
             *       "India": 0.1
             *     }
             */
            destination_shocks?: {
                [key: string]: number;
            };
            /**
             * Discount Rate
             * @description Real discount rate hurdle for annuity valuation
             * @default 0.12
             * @example 0.12
             */
            discount_rate: number;
            /**
             * Variable Cost Share
             * @description Proportion of cash cost that scales with production volume
             * @default 0.65
             * @example 0.65
             */
            variable_cost_share: number;
            /**
             * License Cliff Expiry Shock
             * @description If true, assumes 3-year expiring concession areas fail renewal
             * @default false
             * @example false
             */
            license_cliff_expiry_shock: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_check_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    list_issuers_v1_issuers_get: {
        parameters: {
            query?: {
                /** @description Filter by commodity (e.g. Coal) */
                commodity?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuerSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_issuer_detail_v1_issuers__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_issuer_graph_v1_issuers__symbol__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuerGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mining_sites_geojson_v1_sites_get: {
        parameters: {
            query?: {
                /** @description Filter by commodity (e.g. Coal) */
                commodity?: string | null;
                /** @description Filter by ticker symbol (e.g. ADRO, AADI) */
                issuer?: string | null;
                /** @description Filter sites belonging to in-universe issuers */
                in_universe_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoJSONFeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metric_rankings_v1_rankings_get: {
        parameters: {
            query?: {
                /** @description Metric to rank by: 'ground_truth_score', 'rli_years', 'reserve_backed_value_usd', 'cash_cost_per_ton_usd', 'license_cliff_3y', 'rbv_gap_pct' */
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_national_cost_curve_v1_cost_curve_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostCurveResponse"];
                };
            };
        };
    };
    run_scenario_simulation_v1_scenario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioShockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_flow_overlay_v1_flow_overlay_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowOverlayResponse"];
                };
            };
        };
    };
    get_data_coverage_report_v1_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataCoverageResponse"];
                };
            };
        };
    };
}
