import { test, expect } from "@playwright/test";

test("Mobile profile tabs, metric help and dashboard screening remain usable", async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/issuer/BYAN");
  await expect(page.getByRole("tab", { name: "Overview", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByTestId("valuation-context")).toHaveCount(0);
  await page.getByRole("button", { name: "Metric explanations", exact: true }).first().click();
  await expect(page.locator('[popover]:popover-open')).toContainText("Reserves divided by annual production");
  await page.keyboard.press("Escape");
  await expect(page.locator('[popover]:popover-open')).toHaveCount(0);
  await page.getByRole("tab", { name: "Overview", exact: true }).focus();
  await page.keyboard.press("ArrowRight");
  await expect(page.getByRole("tab", { name: "Valuation", exact: true })).toBeFocused();
  await expect(page.getByTestId("valuation-context")).toBeVisible();
  await page.getByRole("tab", { name: "Operations", exact: true }).click();
  await expect(page.getByTestId("issuer-economics")).toBeVisible();
  await page.getByRole("tab", { name: "Score & coverage", exact: true }).click();
  await expect(page.getByTestId("score-diagnostics")).toBeVisible();
  await page.goto("/dashboard");
  await page.getByLabel("Search issuers", { exact: true }).fill("NO_MATCH");
  await expect(page.getByRole("heading", { name: "No issuers match your filters" })).toBeVisible();
  await page.getByLabel("Search issuers", { exact: true }).fill("BYAN");
  await expect(page.getByTestId("score-row-BYAN")).toBeVisible();
  await expect(page.locator('[data-testid^="score-row-"]')).toHaveCount(1);
  await page.getByText("Valuation & risk matrix", { exact: true }).click();
  const downloading = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export CSV", exact: true }).click();
  const stream = await (await downloading).createReadStream();
  const chunks: Buffer[] = [];
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk));
  const csv = Buffer.concat(chunks).toString("utf8");
  const issuers = await (await request.get("/api/v1/issuers")).json();
  for (const issuer of issuers) expect(csv).toContain(`"${issuer.symbol}"`);
  expect(csv).toContain('"Score Ranking Status"');
  expect(errors).toEqual([]);
});

test("Map grouping, combined filters, selection and reset reflect the published sites", async ({ page, request }) => {
  const sites = (await (await request.get("/api/v1/sites")).json()).features;
  await page.goto("/map");
  await expect(page.getByLabel("Mining site list").getByRole("button")).toHaveCount(sites.length);
  await expect.poll(async () => page.getByTestId("map-cluster").evaluateAll((clusters) => clusters.reduce((sum, cluster) => sum + Number(cluster.getAttribute("data-count")), 0))).toBe(sites.length);
  await page.getByLabel("Issuer filter", { exact: true }).selectOption("AADI");
  const expected = sites.filter((site: { properties: { issuer_symbols?: string[]; issuer_symbol?: string } }) => (site.properties.issuer_symbols?.length ? site.properties.issuer_symbols : [site.properties.issuer_symbol]).includes("AADI"));
  await expect(page.getByLabel("Mining site list").getByRole("button")).toHaveCount(expected.length);
  const province = expected[0].properties.province;
  await page.getByLabel("Province filter", { exact: true }) .selectOption({ label: "South Kalimantan" });
  await expect(page.getByLabel("Mining site list").getByRole("button")).toHaveCount(expected.filter((site: { properties: { province: string } }) => site.properties.province === province).length);
  await page.getByLabel("Mining site list").getByRole("button").first().click();
  await expect(page.getByLabel("Selected site details")).toContainText("AADI");
  await expect(page.getByTestId("offline-map").getByRole("button", { name: /^Select / }).first()).toBeVisible();
  await page.getByLabel("Search sites, provinces, or issuers").fill("NO_MATCH");
  await expect(page.getByLabel("Selected site details")).toHaveCount(0);
  await expect(page.getByLabel("Mining site list")).toContainText("No sites match your filters");
  await page.getByRole("button", { name: "Reset filter", exact: true }).click();
  await expect(page.getByLabel("Mining site list").getByRole("button")).toHaveCount(sites.length);
});
