import type { AiAnswer } from "./types";
import { AI_KIND_LABELS, AI_STATUS_LABELS } from "./presentation";

export function aiBriefMarkdown(answer: AiAnswer): string {
  return [
    `# ${answer.title}`, "", `Generated: ${answer.generated_at}`, `Model: ${answer.model} · Gemini on Vertex AI`,
    `Snapshot: ${answer.snapshot.as_of ?? "See issuer Evidence"} · Run: ${answer.snapshot.run_id ?? "See issuer Evidence"}`,
    `Dataset source: ${answer.snapshot.source_type}. Scope: ${answer.snapshot.scope.join(", ")}.`,
    `Response status: ${AI_STATUS_LABELS[answer.status]}`,
    "", answer.summary.text, `Evidence: ${answer.summary.evidence_ids.join(", ")}`,
    ...answer.findings.flatMap((item) => ["", `## ${AI_KIND_LABELS[item.kind]}: ${item.title}`, "", item.text, "", `Evidence: ${item.evidence_ids.join(", ")}`]),
    "", "## Evidence", ...answer.evidence.flatMap((item) => [`- **${item.id}**: ${item.label}: ${item.value}`, `  Source: ${item.source}. Snapshot: ${item.as_of ?? "Unavailable"}. Quality: ${item.quality}. Reference: ${item.href}.`]),
    ...(answer.follow_up_questions.length ? ["", "## Follow-up research", "", ...answer.follow_up_questions.map((question) => `- ${question}`)] : []),
    "", "The narrative is generated by Gemini. Metric values are supplied by GALI; evidence IDs and numeric placeholders are checked before display. These checks do not prove every interpretation. Review sources and model limitations before drawing conclusions.",
  ].join("\n");
}

export function downloadAiBrief(answer: AiAnswer) {
  const url = URL.createObjectURL(new Blob([aiBriefMarkdown(answer)], { type: "text/markdown;charset=utf-8" }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = `gali-ai-research-${answer.snapshot.scope.slice(0, 2).join("-")}-${answer.generated_at.slice(0, 10)}.md`; anchor.click(); URL.revokeObjectURL(url);
}
