"""0002_core_market_graph_metrics

Revision ID: 0bbeeadf8dff
Revises: c0dbc8ceeb14
Create Date: 2026-08-28 20:49:16.437733+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0bbeeadf8dff"
down_revision: str | None = "c0dbc8ceeb14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS market")
    op.execute("CREATE SCHEMA IF NOT EXISTS graph")
    op.execute("CREATE SCHEMA IF NOT EXISTS metrics")
    op.create_table(
        "commodity_export_destination",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("commodity", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("export_value", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commodity_export_destination")),
        schema="core",
    )
    op.create_table(
        "commodity_price",
        sa.Column("commodity", sa.Text(), nullable=False),
        sa.Column("observed_on", sa.Date(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("commodity", "observed_on", name=op.f("pk_commodity_price")),
        schema="core",
    )
    op.create_table(
        "license_auction",
        sa.Column("wiup_code", sa.String(length=64), nullable=False),
        sa.Column("block_name", sa.Text(), nullable=True),
        sa.Column("phases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("participants", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("wiup_code", name=op.f("pk_license_auction")),
        schema="core",
    )
    op.create_table(
        "mining_company",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=True),
        sa.Column("company_type", sa.Text(), nullable=True),
        sa.Column("key_operation", sa.Text(), nullable=True),
        sa.Column("commodity_types", sa.ARRAY(sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_mining_company")),
        schema="core",
    )
    op.create_index("ix_mining_company_symbol", "mining_company", ["symbol"], unique=False, schema="core")
    op.create_table(
        "mining_contract",
        sa.Column("mine_owner_slug", sa.Text(), nullable=False),
        sa.Column("contractor_slug", sa.Text(), nullable=False),
        sa.Column("mine_owner_name", sa.Text(), nullable=True),
        sa.Column("contractor_name", sa.Text(), nullable=True),
        sa.Column("contract_period_end", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("mine_owner_slug", "contractor_slug", name=op.f("pk_mining_contract")),
        schema="core",
    )
    op.create_table(
        "national_production",
        sa.Column("commodity", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("total_production", sa.Float(), nullable=False),
        sa.Column("yoy_pct", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("commodity", "year", name=op.f("pk_national_production")),
        schema="core",
    )
    op.create_table(
        "province_reserves",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("province", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("commodity", sa.Text(), nullable=False),
        sa.Column("exploration_target", sa.Float(), nullable=True),
        sa.Column("total_inventory", sa.Float(), nullable=True),
        sa.Column("resources", sa.Float(), nullable=True),
        sa.Column("reserves", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_province_reserves")),
        schema="core",
    )
    op.create_table(
        "issuer",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("primary_commodity", sa.String(length=32), nullable=True),
        sa.Column("is_in_universe", sa.Boolean(), nullable=False),
        sa.Column("coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_issuer")),
        schema="graph",
    )
    op.create_table(
        "issuer_mining_link",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("company_slug", sa.Text(), nullable=False),
        sa.Column("effective_ownership_pct", sa.Float(), nullable=False),
        sa.Column("path", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("method", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "company_slug", name=op.f("pk_issuer_mining_link")),
        schema="graph",
    )
    op.create_table(
        "ownership_edge",
        sa.Column("parent_slug", sa.Text(), nullable=False),
        sa.Column("child_slug", sa.Text(), nullable=False),
        sa.Column("percentage_ownership", sa.Float(), nullable=False),
        sa.Column("parent_symbol", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("parent_slug", "child_slug", name=op.f("pk_ownership_edge")),
        schema="graph",
    )
    op.create_table(
        "broker_registry",
        sa.Column("broker_code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=True),
        sa.Column("cohort", sa.String(length=32), nullable=True),
        sa.Column("license_type", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("broker_code", name=op.f("pk_broker_registry")),
        schema="market",
    )
    op.create_table(
        "idx_company",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("sub_sector", sa.Text(), nullable=True),
        sa.Column("market_cap_idr", sa.Float(), nullable=True),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_idx_company")),
        schema="market",
    )
    op.create_index("ix_idx_company_sector", "idx_company", ["sector"], unique=False, schema="market")
    op.create_index("ix_idx_company_sub_sector", "idx_company", ["sub_sector"], unique=False, schema="market")
    op.create_table(
        "run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("code_version", sa.String(length=32), nullable=False),
        sa.Column("data_version", sa.String(length=32), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "status IN ('building', 'validated', 'published', 'failed')", name=op.f("ck_run_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run")),
        schema="metrics",
    )
    op.create_index("ix_metric_run_status", "run", ["status"], unique=False, schema="metrics")
    op.create_table(
        "company_financials",
        sa.Column("company_slug", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=True),
        sa.Column("assets_usd", sa.Float(), nullable=True),
        sa.Column("revenue_usd", sa.Float(), nullable=True),
        sa.Column("revenue_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cost_of_revenue_usd", sa.Float(), nullable=True),
        sa.Column("cost_of_revenue_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("profit_usd", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_slug"],
            ["core.mining_company.slug"],
            name=op.f("fk_company_financials_company_slug_mining_company"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("company_slug", "year", name=op.f("pk_company_financials")),
        schema="core",
    )
    op.create_table(
        "company_performance",
        sa.Column("company_slug", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("commodity_type", sa.Text(), nullable=False),
        sa.Column("commodity_sub_type", sa.Text(), nullable=True),
        sa.Column("mining_operation_status", sa.String(length=32), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("production_volume", sa.Float(), nullable=True),
        sa.Column("sales_volume", sa.Float(), nullable=True),
        sa.Column("overburden_removal_volume", sa.Float(), nullable=True),
        sa.Column("strip_ratio", sa.Float(), nullable=True),
        sa.Column("measurement_year", sa.Integer(), nullable=True),
        sa.Column("proven_reserves_mt", sa.Float(), nullable=True),
        sa.Column("probable_reserves_mt", sa.Float(), nullable=True),
        sa.Column("total_reserves_mt", sa.Float(), nullable=True),
        sa.Column("measured_resources_mt", sa.Float(), nullable=True),
        sa.Column("indicated_resources_mt", sa.Float(), nullable=True),
        sa.Column("inferred_resources_mt", sa.Float(), nullable=True),
        sa.Column("total_resources_mt", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_slug"],
            ["core.mining_company.slug"],
            name=op.f("fk_company_performance_company_slug_mining_company"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("company_slug", "year", "commodity_type", name=op.f("pk_company_performance")),
        schema="core",
    )
    op.create_table(
        "company_product",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_slug", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("product_name", sa.Text(), nullable=False),
        sa.Column("cv_kcal_min", sa.Float(), nullable=True),
        sa.Column("cv_kcal_max", sa.Float(), nullable=True),
        sa.Column("moisture_pct_min", sa.Float(), nullable=True),
        sa.Column("moisture_pct_max", sa.Float(), nullable=True),
        sa.Column("ash_adb_min", sa.Float(), nullable=True),
        sa.Column("ash_adb_max", sa.Float(), nullable=True),
        sa.Column("sulphur_adb_min", sa.Float(), nullable=True),
        sa.Column("sulphur_adb_max", sa.Float(), nullable=True),
        sa.Column("volatile_matter_adb_min", sa.Float(), nullable=True),
        sa.Column("volatile_matter_adb_max", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_slug"],
            ["core.mining_company.slug"],
            name=op.f("fk_company_product_company_slug_mining_company"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_product")),
        schema="core",
    )
    op.create_index(
        "ix_company_product_lookup", "company_product", ["company_slug", "year"], unique=False, schema="core"
    )
    op.create_table(
        "mining_license",
        sa.Column("wiup_code", sa.String(length=64), nullable=False),
        sa.Column("license_number", sa.Text(), nullable=True),
        sa.Column("license_type", sa.String(length=16), nullable=True),
        sa.Column("province", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("license_effective_date", sa.Date(), nullable=True),
        sa.Column("license_expiry_date", sa.Date(), nullable=True),
        sa.Column("activity", sa.Text(), nullable=True),
        sa.Column("licensed_area_ha", sa.Float(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("commodity_type", sa.Text(), nullable=True),
        sa.Column("company_name", sa.Text(), nullable=True),
        sa.Column("cnc", sa.String(length=16), nullable=True),
        sa.Column("generation", sa.String(length=16), nullable=True),
        sa.Column("company_slug", sa.Text(), nullable=True),
        sa.Column("match_confidence", sa.Float(), nullable=True),
        sa.Column("match_method", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_slug"],
            ["core.mining_company.slug"],
            name=op.f("fk_mining_license_company_slug_mining_company"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("wiup_code", name=op.f("pk_mining_license")),
        schema="core",
    )
    op.create_index("ix_mining_license_company_name", "mining_license", ["company_name"], unique=False, schema="core")
    op.create_index("ix_mining_license_company_slug", "mining_license", ["company_slug"], unique=False, schema="core")
    op.create_index("ix_mining_license_expiry", "mining_license", ["license_expiry_date"], unique=False, schema="core")
    op.create_table(
        "mining_site",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("project_name", sa.Text(), nullable=True),
        sa.Column("company_slug", sa.Text(), nullable=True),
        sa.Column("company_name", sa.Text(), nullable=True),
        sa.Column("commodity_type", sa.Text(), nullable=True),
        sa.Column("province", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_slug"],
            ["core.mining_company.slug"],
            name=op.f("fk_mining_site_company_slug_mining_company"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_mining_site")),
        schema="core",
    )
    op.create_index("ix_mining_site_commodity", "mining_site", ["commodity_type"], unique=False, schema="core")
    op.create_index("ix_mining_site_company", "mining_site", ["company_slug"], unique=False, schema="core")
    op.create_table(
        "sales_destination",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_slug", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("commodity_type", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("revenue_usd", sa.Float(), nullable=True),
        sa.Column("pct_of_total_revenue", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("pct_of_sales_volume", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_slug"],
            ["core.mining_company.slug"],
            name=op.f("fk_sales_destination_company_slug_mining_company"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_destination")),
        schema="core",
    )
    op.create_index(
        "ix_sales_destination_lookup", "sales_destination", ["company_slug", "year"], unique=False, schema="core"
    )
    op.create_table(
        "broker_summary_top",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("window_start", sa.Date(), nullable=False),
        sa.Column("window_end", sa.Date(), nullable=False),
        sa.Column("broker_code", sa.String(length=8), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("net_value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["market.idx_company.symbol"],
            name=op.f("fk_broker_summary_top_symbol_idx_company"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_summary_top")),
        schema="market",
    )
    op.create_index(
        "ix_broker_summary_symbol_window",
        "broker_summary_top",
        ["symbol", "window_start", "window_end"],
        unique=False,
        schema="market",
    )
    op.create_table(
        "corporate_action",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["market.idx_company.symbol"],
            name=op.f("fk_corporate_action_symbol_idx_company"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_action")),
        schema="market",
    )
    op.create_index("ix_corporate_action_symbol", "corporate_action", ["symbol", "date"], unique=False, schema="market")
    op.create_table(
        "filing",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("holder_name", sa.Text(), nullable=False),
        sa.Column("holder_type", sa.String(length=32), nullable=True),
        sa.Column("transaction_type", sa.String(length=16), nullable=True),
        sa.Column("shares", sa.Float(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"], ["market.idx_company.symbol"], name=op.f("fk_filing_symbol_idx_company"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filing")),
        schema="market",
    )
    op.create_index("ix_filing_symbol_date", "filing", ["symbol", "date"], unique=False, schema="market")
    op.create_table(
        "foreign_flow",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("net_foreign_inflow", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["market.idx_company.symbol"],
            name=op.f("fk_foreign_flow_symbol_idx_company"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("symbol", "date", name=op.f("pk_foreign_flow")),
        schema="market",
    )
    op.create_table(
        "free_float",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("free_float_pct", sa.Float(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"], ["market.idx_company.symbol"], name=op.f("fk_free_float_symbol_idx_company"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_free_float")),
        schema="market",
    )
    op.create_table(
        "idx_daily_close",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["market.idx_company.symbol"],
            name=op.f("fk_idx_daily_close_symbol_idx_company"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("symbol", "date", name=op.f("pk_idx_daily_close")),
        schema="market",
    )
    op.create_index("ix_idx_daily_date", "idx_daily_close", ["date"], unique=False, schema="market")
    op.create_table(
        "issuer_metrics",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("rli_years", sa.Float(), nullable=True),
        sa.Column("implied_life_years", sa.Float(), nullable=True),
        sa.Column("reserve_life_gap_years", sa.Float(), nullable=True),
        sa.Column("attributable_gross_profit_usd", sa.Float(), nullable=True),
        sa.Column("reserve_backed_value_usd", sa.Float(), nullable=True),
        sa.Column("market_cap_usd", sa.Float(), nullable=True),
        sa.Column("rbv_gap_pct", sa.Float(), nullable=True),
        sa.Column("license_cliff_1y", sa.Float(), nullable=True),
        sa.Column("license_cliff_3y", sa.Float(), nullable=True),
        sa.Column("license_cliff_5y", sa.Float(), nullable=True),
        sa.Column("cnc_coverage_pct", sa.Float(), nullable=True),
        sa.Column("weighted_days_to_expiry", sa.Float(), nullable=True),
        sa.Column("cash_cost_per_ton_usd", sa.Float(), nullable=True),
        sa.Column("realized_price_per_ton_usd", sa.Float(), nullable=True),
        sa.Column("unit_margin_usd", sa.Float(), nullable=True),
        sa.Column("breakeven_benchmark_price_usd", sa.Float(), nullable=True),
        sa.Column("cost_curve_percentile", sa.Float(), nullable=True),
        sa.Column("weighted_cv_kcal", sa.Float(), nullable=True),
        sa.Column("benchmark_grade", sa.String(length=32), nullable=True),
        sa.Column("benchmark_price_usd", sa.Float(), nullable=True),
        sa.Column("quality_discount_pct", sa.Float(), nullable=True),
        sa.Column("destination_hhi", sa.Float(), nullable=True),
        sa.Column("top_destination", sa.String(length=64), nullable=True),
        sa.Column("top_destination_pct", sa.Float(), nullable=True),
        sa.Column("contractor_hhi", sa.Float(), nullable=True),
        sa.Column("contract_cliff_12m", sa.Float(), nullable=True),
        sa.Column("ground_truth_score", sa.Float(), nullable=True),
        sa.Column("component_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["metrics.run.id"], name=op.f("fk_issuer_metrics_run_id_run"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("run_id", "symbol", name=op.f("pk_issuer_metrics")),
        schema="metrics",
    )
    op.create_table(
        "published_pointer",
        sa.Column("singleton", sa.Boolean(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["metrics.run.id"], name=op.f("fk_published_pointer_run_id_run"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("singleton", name=op.f("pk_published_pointer")),
        schema="metrics",
    )
    op.create_table(
        "mining_site_production",
        sa.Column("site_slug", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("production_volume", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("strip_ratio", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_slug"],
            ["core.mining_site.slug"],
            name=op.f("fk_mining_site_production_site_slug_mining_site"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("site_slug", "year", name=op.f("pk_mining_site_production")),
        schema="core",
    )
    op.alter_column(
        "data_coverage", "detail", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False, schema="ops"
    )
    op.drop_column("data_coverage", "ratio", schema="ops")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_coverage",
        sa.Column("ratio", sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=True),
        schema="ops",
    )
    op.alter_column(
        "data_coverage", "detail", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True, schema="ops"
    )
    op.drop_table("mining_site_production", schema="core")
    op.drop_table("published_pointer", schema="metrics")
    op.drop_table("issuer_metrics", schema="metrics")
    op.drop_index("ix_idx_daily_date", table_name="idx_daily_close", schema="market")
    op.drop_table("idx_daily_close", schema="market")
    op.drop_table("free_float", schema="market")
    op.drop_table("foreign_flow", schema="market")
    op.drop_index("ix_filing_symbol_date", table_name="filing", schema="market")
    op.drop_table("filing", schema="market")
    op.drop_index("ix_corporate_action_symbol", table_name="corporate_action", schema="market")
    op.drop_table("corporate_action", schema="market")
    op.drop_index("ix_broker_summary_symbol_window", table_name="broker_summary_top", schema="market")
    op.drop_table("broker_summary_top", schema="market")
    op.drop_index("ix_sales_destination_lookup", table_name="sales_destination", schema="core")
    op.drop_table("sales_destination", schema="core")
    op.drop_index("ix_mining_site_company", table_name="mining_site", schema="core")
    op.drop_index("ix_mining_site_commodity", table_name="mining_site", schema="core")
    op.drop_table("mining_site", schema="core")
    op.drop_index("ix_mining_license_expiry", table_name="mining_license", schema="core")
    op.drop_index("ix_mining_license_company_slug", table_name="mining_license", schema="core")
    op.drop_index("ix_mining_license_company_name", table_name="mining_license", schema="core")
    op.drop_table("mining_license", schema="core")
    op.drop_index("ix_company_product_lookup", table_name="company_product", schema="core")
    op.drop_table("company_product", schema="core")
    op.drop_table("company_performance", schema="core")
    op.drop_table("company_financials", schema="core")
    op.drop_index("ix_metric_run_status", table_name="run", schema="metrics")
    op.drop_table("run", schema="metrics")
    op.drop_index("ix_idx_company_sub_sector", table_name="idx_company", schema="market")
    op.drop_index("ix_idx_company_sector", table_name="idx_company", schema="market")
    op.drop_table("idx_company", schema="market")
    op.drop_table("broker_registry", schema="market")
    op.drop_table("ownership_edge", schema="graph")
    op.drop_table("issuer_mining_link", schema="graph")
    op.drop_table("issuer", schema="graph")
    op.drop_table("province_reserves", schema="core")
    op.drop_table("national_production", schema="core")
    op.drop_table("mining_contract", schema="core")
    op.drop_index("ix_mining_company_symbol", table_name="mining_company", schema="core")
    op.drop_table("mining_company", schema="core")
    op.drop_table("license_auction", schema="core")
    op.drop_table("commodity_price", schema="core")
    op.drop_table("commodity_export_destination", schema="core")
    # ### end Alembic commands ###
