"""0001_raw_ops_initial

Revision ID: c0dbc8ceeb14
Revises:
Create Date: 2026-08-28 19:51:06.878752+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c0dbc8ceeb14"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS raw")
    op.execute("CREATE SCHEMA IF NOT EXISTS ops")
    op.create_table(
        "api_key",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("rate_limit_per_min", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_key")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_key_key_hash")),
        schema="ops",
    )
    op.create_table(
        "credit_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(length=8), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("raw_response_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("tier IN ('cold', 'warm', 'hot')", name=op.f("ck_credit_ledger_tier_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_ledger")),
        schema="ops",
    )
    op.create_index("ix_credit_ledger_occurred", "credit_ledger", ["occurred_at"], unique=False, schema="ops")
    op.create_table(
        "data_coverage",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("numerator", sa.Integer(), nullable=False),
        sa.Column("denominator", sa.Integer(), nullable=False),
        sa.Column("ratio", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_coverage")),
        schema="ops",
    )
    op.create_index("ix_data_coverage_metric", "data_coverage", ["metric", "captured_at"], unique=False, schema="ops")
    op.create_table(
        "responses",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("params_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("credits_charged", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(length=8), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.CheckConstraint("tier IN ('cold', 'warm', 'hot')", name=op.f("ck_responses_tier_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_responses")),
        sa.UniqueConstraint("endpoint", "params_hash", "fetched_at", name="uq_responses_endpoint_params_fetched"),
        schema="raw",
    )
    op.create_index(
        "ix_responses_lookup", "responses", ["endpoint", "params_hash", "fetched_at"], unique=False, schema="raw"
    )
    op.create_index("ix_responses_run", "responses", ["run_id"], unique=False, schema="raw")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_responses_run", table_name="responses", schema="raw")
    op.drop_index("ix_responses_lookup", table_name="responses", schema="raw")
    op.drop_table("responses", schema="raw")
    op.drop_index("ix_data_coverage_metric", table_name="data_coverage", schema="ops")
    op.drop_table("data_coverage", schema="ops")
    op.drop_index("ix_credit_ledger_occurred", table_name="credit_ledger", schema="ops")
    op.drop_table("credit_ledger", schema="ops")
    op.drop_table("api_key", schema="ops")
    # ### end Alembic commands ###
